from crewai import Task
from ..BaseAgent import BaseAgent
from models.ProviderLLM import ProviderLLM
from datetime import datetime

class InventoryAnalysisReportingSpecialist(BaseAgent):
    def __init__(self):
        provider = ProviderLLM()
        llm = provider.get_llm()
        
        super().__init__(
            name="Inventory Analysis & Reporting Specialist",
            role="Senior Inventory Analysis & Strategic Reporting Specialist",
            goal="Create comprehensive inventory reports with clear sections for each analysis type and actionable insights",
            backstory="Senior inventory analyst with 10+ years experience in supply chain optimization. Expert in transforming complex data into executive-ready reports with strategic recommendations.",
            llm=llm,
            allow_delegation=False,
        )
    
    def get_task(self):
        return Task(
            description="\n".join([
                "Create a comprehensive inventory management report with separate, clearly formatted sections for each analysis area.",
                "",
                "## Analysis Requirements:",
                "",
                "**1. Executive Summary Section:**",
                "- Business impact overview",
                "- Critical findings and priorities",
                "- Financial implications",
                "",
                "**2. Critical Alerts Section:**",
                "- Immediate stockout risks",
                "- Overstocked items",
                "- Supplier performance issues",
                "- Each alert: severity level, impact, action required, timeline",
                "",
                "**3. KPI Dashboard Section:**",
                "- Inventory turnover by category",
                "- Service level performance",
                "- Carrying cost analysis",
                "- Forecast accuracy metrics",
                "",
                "**4. ABC Analysis Section:**",
                "- Classification breakdown with insights",
                "- Category performance analysis",
                "- Optimization recommendations",
                "",
                "**5. Action Plan Section:**",
                "- Immediate actions (0-48 hours)",
                "- Short-term improvements (1-4 weeks)",
                "- Long-term strategy (1-6 months)",
                "- Each action: objective, timeline, success metrics",
                "",
                "## Formatting Requirements:",
                "- Use clear markdown headers for each section",
                "- Present data in well-formatted tables",
                "- Include bullet points for key insights",
                "- Separate each analysis type clearly",
                "- Avoid CSV-style data presentation"
            ]),
            agent=self.get_agent(),
            expected_output="\n".join([
                "A professional markdown report with the following structure:",
                "",
                "# Inventory Management Analysis Report",
                f"**Company:** {self.get_config().COMPANY_NAME}",
                f"**Date:** {datetime.now().strftime('%Y-%m-%d, %H:%M')}",
                "",
                "## 📊 Executive Summary",
                "- Key findings summary (200-300 words)",
                "- Critical business impacts",
                "- Priority recommendations",
                "",
                "## 🚨 Critical Alerts",
                "| Alert Type | Item | Severity | Impact | Action Required | Timeline |",
                "|------------|------|----------|--------|-----------------|----------|",
                "| ... | ... | ... | ... | ... | ... |",
                "",
                "## 📈 Key Performance Indicators",
                "### Inventory Turnover",
                "| Category | Current | Target | Status | Trend |",
                "|----------|---------|--------|--------|-------|",
                "| ... | ... | ... | ... | ... |",
                "",
                "### Service Levels",
                "| Metric | Current | Target | Gap | Action |",
                "|--------|---------|--------|-----|--------|",
                "| ... | ... | ... | ... | ... |",
                "",
                "## 🔍 ABC Analysis",
                "### Classification Summary",
                "| Class | Items | Value % | Recommendations |",
                "|-------|-------|---------|----------------|",
                "| A | ... | ... | ... |",
                "| B | ... | ... | ... |",
                "| C | ... | ... | ... |",
                "",
                "## 🎯 Action Plan",
                "### Immediate Actions (0-48 hours)",
                "1. **Action 1:** Description, timeline, responsible party",
                "2. **Action 2:** Description, timeline, responsible party",
                "",
                "### Short-term Improvements (1-4 weeks)",
                "1. **Initiative 1:** Objective, resources needed, success metrics",
                "2. **Initiative 2:** Objective, resources needed, success metrics",
                "",
                "### Long-term Strategy (1-6 months)",
                "1. **Strategy 1:** Goals, ROI projection, implementation plan",
                "2. **Strategy 2:** Goals, ROI projection, implementation plan",
                "",
                "## 📋 Implementation Timeline",
                "| Phase | Duration | Key Milestones | Success Metrics |",
                "|-------|----------|----------------|-----------------|",
                "| ... | ... | ... | ... |",
                "",
                f"**please use the Language:** {self.get_config().LANGUAGE} **for this report",
                "",
                "**Quality Requirements:**",
                "- Each section must be clearly separated with proper headers",
                "- All tables must be properly formatted with consistent columns",
                "- No raw CSV data presentation",
                "- Include specific, measurable recommendations",
                "- Use professional, executive-friendly language"
            ]),
            
            output_file="results/inventory_management/comprehensive_inventory_analysis_report.md"
        )
        
        