from crewai import Task
from ..BaseAgent import BaseAgent
from models.ProviderLLM import ProviderLLM
from datetime import datetime

class InventoryAnalysisReportingSpecialist(BaseAgent):
    def __init__(self):
        provider = ProviderLLM()
        llm = provider.get_llm()
        
        super().__init__(
            name="Inventory Analysis & Reporting Specialist",
            role="Senior Inventory Analysis & Strategic Reporting Specialist",
            goal="Generate comprehensive, data-driven inventory reports with actionable insights and strategic recommendations for executive decision-making",
            backstory="\n".join([
                "You are a senior inventory analyst with 10+ years of experience in supply chain optimization and business intelligence.",
                "You specialize in transforming complex inventory data into executive-ready reports and strategic insights.",
                "Your expertise includes ABC analysis, demand forecasting, KPI development, and creating actionable business recommendations.",
                "You have a proven track record of identifying cost-saving opportunities and operational improvements through data analysis.",
                "You excel at presenting technical findings in clear, business-focused language that drives decision-making at all organizational levels."
            ]),
            llm=llm,
            allow_delegation=False,
                    )
    
    def get_task(self):
        return Task(
            description="\n".join([
                "Generate a comprehensive inventory management report that provides strategic insights and actionable recommendations.",
                "",
                "## Core Analysis Requirements:",
                "1. **Data Processing & Validation:**",
                "   - Analyze inventory data quality and completeness",
                "   - Identify data anomalies and inconsistencies",
                "   - Validate ABC classification accuracy",
                "",
                "2. **Strategic Executive Summary:**",
                "   - Provide high-level business impact summary",
                "   - Highlight critical business risks and opportunities",
                "   - Present key financial implications",
                "   - Include performance benchmarks and trends",
                "",
                "3. **Critical Alerts & Risk Assessment:**",
                "   - Identify immediate stockout risks (items below safety stock)",
                "   - Flag reorder point breaches requiring urgent attention",
                "   - Highlight overstocked items with carrying cost implications",
                "   - Assess supplier performance and delivery risks",
                "   - Categorize alerts by severity and business impact",
                "",
                "4. **Comprehensive KPI Dashboard:**",
                "   - Inventory turnover ratio by category and ABC class",
                "   - Service level performance and fill rates",
                "   - Carrying cost analysis and optimization opportunities",
                "   - Stockout frequency and financial impact",
                "   - Demand forecast accuracy metrics",
                "   - Lead time variability analysis",
                "",
                "5. **Strategic Action Plan:**",
                "   - Immediate actions (0-48 hours) with priority ranking",
                "   - Short-term improvements (1-4 weeks) with resource requirements",
                "   - Long-term strategic initiatives (1-6 months) with ROI projections",
                "   - Resource allocation recommendations",
                "   - Implementation timeline with milestones",
                "   - Success metrics and monitoring framework",
                "",
                "6. **Business Intelligence Insights:**",
                "   - Category performance analysis with improvement opportunities",
                "   - Seasonal trend identification and planning recommendations",
                "   - Supplier performance evaluation and optimization suggestions",
                "   - Cost reduction opportunities with quantified benefits",
                "   - Process improvement recommendations",
                "",
                "## Technical Specifications:",
                "- Use professional markdown formatting with clear hierarchy",
                "- Include executive-friendly visualizations descriptions",
                "- Provide quantified recommendations with financial impact",
                "- Ensure all recommendations are specific, measurable, and time-bound",
                "- Include risk assessment for each recommendation",
                "- Add contact information and escalation procedures"
            ]),
            agent=self.get_agent(),
            expected_output="\n".join([
                "A comprehensive, executive-ready Markdown (.md) report containing:",
                "",
                "## 📊 Required Sections:",
                "",
                "### 1. Executive Summary (300-500 words)",
                "- Strategic overview with key business impacts",
                "- Critical findings and immediate priorities",
                "- Financial implications and cost-benefit analysis",
                "- High-level recommendations with expected outcomes",
                "",
                "### 2. Critical Alerts Dashboard",
                "- Immediate action items with severity levels (Critical/High/Medium)",
                "- Stockout risk assessment with financial impact",
                "- Overstocking alerts with carrying cost implications",
                "- Supplier performance issues requiring attention",
                "- Each alert must include: impact assessment, recommended action, timeline, responsible party",
                "",
                "### 3. Key Performance Indicators (KPIs)",
                "- Current performance vs. targets with trend analysis",
                "- Inventory turnover metrics by category and ABC classification",
                "- Service level performance with gap analysis",
                "- Cost efficiency metrics (carrying costs, stockout costs)",
                "- Demand forecast accuracy with improvement opportunities",
                "- Benchmarking against industry standards",
                "",
                "### 4. Detailed Data Analysis",
                "- ABC classification summary with strategic insights",
                "- Category performance analysis with recommendations",
                "- Inventory distribution analysis with optimization opportunities",
                "- Trend analysis with seasonal considerations",
                "- Complete data tables with proper markdown formatting",
                "",
                "### 5. Strategic Action Plan",
                "- **Immediate Actions (0-48 hours):** Urgent interventions with specific steps",
                "- **Short-term Initiatives (1-4 weeks):** Operational improvements with resource requirements",
                "- **Long-term Strategy (1-6 months):** Strategic initiatives with ROI projections",
                "- Each action item must include: objective, methodology, timeline, success metrics, risk assessment",
                "",
                "### 6. Implementation Framework",
                "- Resource allocation requirements",
                "- Timeline with key milestones",
                "- Success metrics and KPI monitoring",
                "- Risk mitigation strategies",
                "- Escalation procedures and contact information",
                "",
                "## 🎯 Quality Standards:",
                "- Professional formatting with consistent styling",
                "- Clear, actionable language suitable for executive consumption",
                "- Quantified recommendations with measurable outcomes",
                "- Comprehensive yet concise presentation",
                "- Strategic focus with operational detail",
                "- Risk-aware recommendations with mitigation strategies",
                "",
                "## 📋 Deliverable Format:",
                "- File format: Markdown (.md)",
                "- Length: 2000-4000 words",
                "- Structure: Hierarchical with clear sections",
                "- Style: Professional, data-driven, actionable",
                "- Audience: C-level executives, operations managers, inventory specialists",
                f"please use the language report {self.get_config().LANGUAGE}",
                f"Data Report is{datetime.now().strftime('%Y-%m-%d, %H:%M')}",
                f"the campany nama is {self.get_config().COMPANY_NAME}",
                "finally, make sure the tables are very consistent"
            ]),
            output_file="results/inventory_management/comprehensive_inventory_analysis_report.md"
        )
            
        