import React from 'react';
import { ArrowLeft, Download, FileText } from 'lucide-react';
import { AnalysisResponse } from '../types';

interface ReportViewerProps {
  data: AnalysisResponse; 
  onBack: () => void;
}

export const ReportViewer: React.FC<ReportViewerProps> = ({ data, onBack }) => {
  
  const [pdfUrl, setPdfUrl] = React.useState<string | null>(data.pdfUrl || null);
  const [loading, setLoading] = React.useState<boolean>(!data.pdfUrl);

  const handleDownload = () => {
    if (!pdfUrl) return;
    const link = document.createElement('a');
    link.href = pdfUrl;
    link.download = 'Data_Analysis_Report.pdf';
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  return (
    <div className="h-full flex flex-col bg-slate-50 min-h-[600px]">
      {/* Toolbar */}
      <div className="bg-white border-b border-slate-200 px-6 py-4 flex items-center justify-between sticky top-0 z-40 shadow-sm">
        <div className="flex items-center">
          <button onClick={onBack} className="mr-4 p-2 rounded-full hover:bg-slate-100 text-slate-500 transition-colors">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h2 className="text-lg font-bold text-slate-800 flex items-center">
              <FileText className="w-5 h-5 mr-2 text-indigo-600" />
              Analysis Report
            </h2>
            <p className="text-xs text-slate-500">
              Generated by {data.Agent_name} • {new Date(data.created_at).toLocaleString()}
            </p>
          </div>
        </div>

        <button
          onClick={handleDownload}
          disabled={!pdfUrl}
          className="flex items-center px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm font-medium hover:bg-indigo-700 disabled:opacity-50"
        >
          <Download className="w-4 h-4 mr-2" />
          Download PDF
        </button>
      </div>

      {/* PDF Viewer Container */}
      {/* <div className="flex-1 p-4 lg:p-8 h-[80vh]"> */}
      {/* <div className="flex-1 w-full max-w-5xl mx-auto p-2 lg:p-4 h-[calc(100vh-100px)]"> */}
      <div className="fixed inset-0 flex flex-col"></div>
      <div className="flex-1 overflow-hidden"> 
        {loading ? (
          <div className="flex flex-col items-center justify-center h-full space-y-4">
             <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div>
             <p className="text-slate-500">Preparing your report...</p>
          </div>
        ) : pdfUrl ? (
          // <iframe 
          //   src={`${pdfUrl}#toolbar=0&navpanes=0`} 
          //   className="w-full h-full border rounded-xl shadow-lg bg-white" 
          //   title="Data Analysis Report"
          // />
          // <iframe 
          //   src={`${pdfUrl}#view=FitH&toolbar=1`} 
          //   className="w-full h-full border-none rounded-lg shadow-2xl bg-white" 
          //   title="Data Analysis Report"
          // />

          <iframe 
            src={`${pdfUrl}#view=FitH`} 
            className="w-full h-full border rounded-xl shadow-lg bg-white" 
            title="Data Analysis Report"
          />
        ) : (
          <div className="text-center p-10 bg-red-50 text-red-600 rounded-xl border border-red-100">
            Could not locate the generated PDF. Please try running the analysis again.
          </div>
        )}
      </div>
    </div>
  );
};