services:
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/pgvectorsql/data
    environment:
    
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  pgvector_data:  

# services:
#   # 🧠 PostgreSQL pgvector
#   pgvector:
#     image: pgvector/pgvector:0.8.0-pg17
#     container_name: pgvector
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgvector_data:/var/lib/pgvectorsql/data
#     environment:
    
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#     networks:
#       - backend
#     restart: always

#   # ⚙️ FastAPI Backend
#   backend:
#     build:
#       context: ../src          
#       dockerfile: backend/Dockerfile
#     container_name: backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ../src/backend:/app    
#     depends_on:
#       - pgvector
#     networks:
#       - backend

#   # 🌐 React Frontend
#   frontend:
#     build: ./frontend
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     depends_on:
#       - backend
#     networks:
#       - backend

# volumes:
#   pgvector_data:

# networks:
#   backend:
#     name: backend
