from .MarketingStratgeyPlanner import ContentPlanner
from .MarketingStratgeyPlanner import MarketingStrategist
from .MarketingStratgeyPlanner import SWOTAnalyst
from .MarketingStratgeyPlanner import TranslationEnglishArabic

from .InventoryManagment import DataProcessing
from .InventoryManagment import DemandForecastingAnalyst
from .InventoryManagment import InventoryOptimizationExpert
from .InventoryManagment import InventoryAnalysisReportingSpecialist
from .InventoryManagment import DataVisualizationExpert
from .InventoryManagment import InventoryReportWriter

from ..Prompts.AnalysisReportPrompt import description_prompt, expected_output_prompt
from ..Prompts.DataprocessingPrompt import Data_processingprompt