from .MarketingStratgeyPlanner import ContentPlanner
from .MarketingStratgeyPlanner import MarketingStrategist
from .MarketingStratgeyPlanner import SWOTAnalyst
from .MarketingStratgeyPlanner import TranslationEnglishArabic

from .InventoryManagment import DataAnalysisSpecialist
from .InventoryManagment import DemandForecastingAnalyst
from .InventoryManagment import InventoryOptimizationExpert
from .InventoryManagment import InventoryAnalysisReportingSpecialist
from .InventoryManagment import DataVisualizationExpert

from ..Prompts.InventoryAnalysisReportPrompt import finally_description_prompt, finally_description_prompt
