from string import Template
from datetime import datetime


finally_description_prompt =Template("\n".join([
                "Create a comprehensive inventory management report with separate, clearly formatted sections for each analysis area.",
                "",
                "## Analysis Requirements:",
                "",
                "**1. Executive Summary Section:**",
                "- Business impact overview",
                "- Critical findings and priorities",
                "- Financial implications",
                "",
                "**2. Critical Alerts Section:**",
                "- Immediate stockout risks",
                "- Overstocked items",
                "- Supplier performance issues",
                "- Each alert: severity level, impact, action required, timeline",
                "",
                "**3. KPI Dashboard Section:**",
                "- Inventory turnover by category",
                "- Service level performance",
                "- Carrying cost analysis",
                "- Forecast accuracy metrics",
                "",
                "**4. ABC Analysis Section:**",
                "- Classification breakdown with insights",
                "- Category performance analysis",
                "- Optimization recommendations",
                "",
                "**5. Action Plan Section:**",
                "- Immediate actions (0-48 hours)",
                "- Short-term improvements (1-4 weeks)",
                "- Long-term strategy (1-6 months)",
                "- Each action: objective, timeline, success metrics",
                "",
                "## Formatting Requirements:",
                "- Use clear markdown headers for each section",
                "- Present data in well-formatted tables",
                "- Include bullet points for key insights",
                "- Separate each analysis type clearly",
                "- Avoid CSV-style data presentation"
            ]))

finally_expected_output_prompt=Template("\n".join([
    "# 📊 Executive Inventory Strategy Report – Full Advisory Format",
    "",
    "**Client:** $COMPANY_NAME",
    "**Industry:** $INDUSTRY_NAME",
    f"**Date:** {datetime.now().strftime('%Y-%m-%d, %H:%M')}",
    "**Prepared By:** Senior Inventory Optimization Consultant",
    "**Language:** $Language — Please write all report content, labels, and descriptions in this language.",
    "",
    "> ⚠️ Note: Ensure each analytical table includes **at least 10 products/items**, sorted by priority or impact (from most critical to least). Prioritize items based on expiry risk, financial exposure, turnover rate, or classification weight.",
    "",
    "## 🔷 Executive Summary",
    "- Provide a strategic overview with maximum insight and minimum fluff (250–300 words).",
    "- Identify key inventory inefficiencies, risks, and value leaks.",
    "- Align findings with global best practices (SCOR, APICS, Lean, DDMRP).",
    "",
    "## 🚨 High-Risk & Strategic Exposure Items",
    "| Risk Type | SKU | Root Cause | Severity | Financial Impact | Strategic Action |",
    "|-----------|-----|------------|----------|------------------|------------------|",
    "| (Top 10 risks – sorted from highest exposure to lowest) |",
    "",
    "## ⌛ Expiry Risk Report – Shelf-Life Critical Items",
    "### ⚠️ Items Expiring Within Next 60 Days",
    "| SKU | Product Name | Expiry Date | Qty | Days Remaining | Priority Level | Recommended Action |",
    "|-----|--------------|-------------|-----|----------------|----------------|---------------------|",
    "| (Include 10 products, sorted by earliest expiry & highest volume) |",
    "",
    "### ❌ Already Expired Inventory",
    "| SKU | Product Name | Expired On | Qty | Financial Value | Treatment Plan |",
    "|-----|--------------|------------|-----|-----------------|----------------|",
    "| (Include top 10 expired items by cost or quantity) |",
    "",
    "## 📈 KPI Dashboard – Key Inventory Metrics",
    "| KPI | Current | Target | Gap | Impact Level | Action Required |",
    "|-----|---------|--------|-----|---------------|------------------|",
    "- Include actionable KPIs (e.g., Turnover, Fill Rate, Carrying Cost).",
    "",
    "## 🔍 ABC Inventory Analysis – Top Value SKUs",
    "### Top 10 High-Value 'A' Class Items",
    "| SKU | Product Name | Inventory Value | % of Total | Monthly Movement | Recommendation |",
    "|-----|--------------|-----------------|-------------|------------------|----------------|",
    "",
    "## 🔁 XYZ Analysis – Demand Variability (Top 10)",
    "| SKU | Demand Pattern (X/Y/Z) | Std Dev | Sales Consistency | Category | Action |",
    "|-----|------------------------|---------|-------------------|----------|--------|",
    "",
    "## 💰 Financial Impact Breakdown",
    "- Total capital tied in excess stock: $___",
    "- Estimated stockout loss: $___",
    "- Expired stock loss: $___",
    "- Working capital recovery potential: $___",
    "",
    "## 🎯 Strategic Roadmap",
    "### Phase 1 – Immediate (0–7 days)",
    "- Restock top 10 most-critical SKUs.",
    "- Quarantine & document expired inventory.",
    "",
    "### Phase 2 – Short-Term (1–6 weeks)",
    "- Implement FEFO (First-Expire-First-Out) logic for top 10 at-risk SKUs.",
    "- Adjust min/max stock levels based on ABC-XYZ matrix.",
    "",
    "### Phase 3 – Long-Term (2–6 months)",
    "- Integrate expiry tracking in inventory software.",
    "- Adopt predictive analytics for demand & expiry risk.",
    "",
    "## 📋 Execution Timeline",
    "| Task | Owner | Due Date | Milestone | Success Metric |",
    "|------|--------|----------|-----------|----------------|",
    "",
    "**Important Reporting Guidelines:**",
   
    "- All tables should have **10 items at minimum**, sorted by impact or priority.",
    "- Do not output raw data — only professional insights.",
    "- All tables should have **10 items at minimum**, sorted by impact or priority.",
    "- Do not output raw data — only professional insights.",
    "- Format all tables using markdown with `|` separators.",
    "- Maintain consulting-level tone throughout the report.",
    "- Use real-world business vocabulary and focus on executive action."
]))

