from .AgentProvider import DataProcessing
from .AgentProvider import DemandForecastingAnalyst
from .AgentProvider import InventoryOptimizationExpert
from .AgentProvider import InventoryAnalysisReportingSpecialist
from .AgentProvider import DataVisualizationExpert
#______________________________________________________________
from .AgentProvider import TranslationEnglishArabic